<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>InternshipManagement.API</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\InternshipManagement.BLL\InternshipManagement.BLL.csproj" />
    <ProjectReference Include="..\InternshipManagement.DAL\InternshipManagement.DAL.csproj" />
  </ItemGroup>
</Project>
