import { Link, useLocation } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'

export default function Layout({children}) {
 const {user,logout}=useAuth(); const loc=useLocation(); const role=user?.maVaiTro
 const groups=role==='VT02'?[['ĐIỀU HÀNH & QUẢN LÝ',[['/khoa','▦','Tổng quan điều hành'],['/khoa/dot-thuc-tap','▣','Quản lý đợt thực tập'],['/khoa/doanh-nghiep','▦','Doanh nghiệp & tiếp nhận'],['/khoa/dang-ky','♧','Đăng ký & xét duyệt'],['/khoa/phan-bo','♙','Phân bổ & phân công GVHD'],['/khoa/theo-doi','⌁','Theo dõi tiến độ toàn khóa'],['/khoa/hoi-dong','☷','Hội đồng & chấm điểm CLO']]],['BÁO CÁO & HỌC VỤ',[['/khoa/thong-ke','▤','Thống kê & báo cáo'],['/khoa/tai-khoan','♙','Tài khoản & phân quyền'],['/khoa/tieu-chi','☷','Cấu hình tiêu chí & CLO']]]]:role==='VT01'?[['QUẢN TRỊ HỆ THỐNG',[['/admin','♙','Tài khoản & phân quyền']]]]:[['SINH VIÊN',[['/dashboard','▦','Tổng quan'],['/ai','✦','AI gợi ý & đánh giá']]]]
 const activeLabel=groups.flatMap(([,links])=>links).find(([to])=>loc.pathname===to)?.[2]||user?.tenVaiTro||'Cổng thực tập'
 return <div className="app-shell"><aside className="sidebar"><div className="side-brand"><span>FIT</span><div>FIT PORTAL<small>Quản lý thực tập tốt nghiệp</small></div></div><div className="sidebar-groups">{groups.map(([group,links])=><section key={group}><div className="sidebar-label">{group}</div><nav>{links.map(([to,icon,label])=><Link key={to} className={loc.pathname===to?'selected':''} to={to}><span>{icon}</span>{label}</Link>)}</nav></section>)}</div><div className="sidebar-bottom"><div className="user-mini"><strong>{user?.hoTen||user?.tenDangNhap}</strong><span>{user?.tenVaiTro}</span></div><Link className="account-link" to="/change-password">Đổi mật khẩu</Link><button className="logout" onClick={logout}>↪ Đăng xuất</button></div></aside><main className="main-content"><header className="portal-topbar"><div>FIT Portal <span>/</span> <strong>{activeLabel}</strong></div><div className="portal-profile"><span className="portal-avatar">{(user?.hoTen||user?.tenDangNhap||'U').slice(0,1).toUpperCase()}</span><div><strong>{user?.hoTen||user?.tenDangNhap}</strong><small>{user?.tenVaiTro}</small></div></div></header>{children}</main></div>
}
