import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import Layout from '../../components/Layout'
import apiClient from '../../services/api'

export default function KhoaCommitteePage() {
  const [rounds, setRounds] = useState([])
  const [round, setRound] = useState('')
  const [data, setData] = useState(null)
  const [search, setSearch] = useState('')
  const [selected, setSelected] = useState(null)
  const [scores, setScores] = useState({})
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const load = async () => { try { const r = await apiClient.get('/khoa/clo', { params: round ? { maDot: round } : {} }); setData(r.data); setError('') } catch (e) { setError(e.response?.data?.message || 'Không tải được số liệu chấm điểm CLO.') } }
  useEffect(() => { apiClient.get('/khoa/dot-thuc-tap').then(r => setRounds(r.data || [])).catch(() => {}) }, [])
  useEffect(() => { load() }, [round])
  const rows = useMemo(() => (data?.assessments || []).filter(x => !search || `${x.maSinhVien} ${x.sinhVien} ${x.lop} ${x.dot}`.toLowerCase().includes(search.toLowerCase())), [data, search])
  const exportCsv = () => { const values = [['MSSV','Sinh viên','Lớp','Đợt','Điểm tổng','Ngày chấm'], ...rows.map(x => [x.maSinhVien,x.sinhVien,x.lop,x.dot,x.tongDiem ?? '',x.ngayCham ? String(x.ngayCham).slice(0,10) : ''])]; const csv = '\uFEFF' + values.map(r => r.map(v => `"${String(v).replaceAll('"','""')}"`).join(',')).join('\r\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); a.download = 'thong-ke-cham-diem-clo.csv'; a.click(); URL.revokeObjectURL(a.href) }
  const beginEdit = item => { setSelected(item); setScores(Object.fromEntries((data?.criteria||[]).map(c=>[c.maTieuChi,item.chiTiet?.find(x=>x.maTieuChi===c.maTieuChi)?.diemCham??0]))) }
  const saveAssessment = async e => { e.preventDefault(); setSaving(true); setError(''); try { await apiClient.put(`/khoa/clo/${encodeURIComponent(selected.maPhieu)}`,{chiTiet:(data?.criteria||[]).map(c=>({maTieuChi:c.maTieuChi,diemCham:Number(scores[c.maTieuChi]||0)}))}); setSelected(null); await load() } catch(e) { setError(e.response?.data?.message||'Không lưu được phiếu chấm.') } finally { setSaving(false) } }
  return <Layout><div className="khoa-page-heading"><div><span className="eyebrow">HỘI ĐỒNG & ĐẢM BẢO CHẤT LƯỢNG</span><h1>Thống kê chuẩn đầu ra CLO / ABET</h1><p>Tổng hợp phiếu chấm thực tập và kết quả theo từng tiêu chí từ cơ sở dữ liệu.</p></div><div className="khoa-actions"><button className="primary" onClick={exportCsv} disabled={!rows.length}>Xuất CSV</button><button className="small" onClick={() => window.print()}>In / Lưu PDF</button></div></div>
    {error && <div className="alert error">{error}</div>}
    <div className="khoa-filter-card"><label>Đợt thực tập<select value={round} onChange={e=>setRound(e.target.value)}><option value="">Tất cả các đợt</option>{rounds.map(x=><option key={x.maSo} value={x.maSo}>{x.tenDot} · {x.namHoc}</option>)}</select></label><input placeholder="Tìm sinh viên, MSSV, lớp..." value={search} onChange={e=>setSearch(e.target.value)}/><Link to="/khoa/tieu-chi" className="secondary-link">Cấu hình tiêu chí CLO →</Link></div>
    <div className="khoa-stat-grid four"><Stat label="Điểm trung bình" value={`${data?.averageScore ?? 0} / 10`} note="Trên các phiếu đã chấm"/><Stat label="Phiếu đánh giá" value={data?.total ?? 0} note="Sinh viên có phiếu trong đợt"/><Stat label="Đã chấm" value={data?.complete ?? 0} note="Đã có điểm tổng hợp"/><Stat label="Chờ chấm" value={data?.pending ?? 0} note="Phiếu chưa có điểm"/></div>
    <section className="khoa-panel"><div className="khoa-panel-head"><div><h2>Ma trận định lượng chuẩn đầu ra</h2><p>Điểm trung bình từng tiêu chí và mức tối đa được cấu hình.</p></div></div><div className="clo-matrix">{(data?.criteria || []).map((c,i)=><div className="clo-matrix-row" key={c.maTieuChi}><div className="clo-matrix-title"><span className="clo-code">{c.maTieuChi}</span><strong>{c.tenTieuChi}</strong><span>{c.average.toFixed(2)} / {c.diemToiDa}</span></div><div className="clo-track"><div style={{width:`${Math.min(100,c.average/c.diemToiDa*100)}%`,background:['#155eef','#2563eb','#075985','#6d5ce8'][i%4]}}/></div><small>{c.submissions} lượt đánh giá · đạt {c.diemToiDa ? Math.round(c.average/c.diemToiDa*100) : 0}% điểm tối đa</small></div>)}{!data?.criteria?.length&&<p className="empty-state">Chưa cấu hình tiêu chí. <Link to="/khoa/tieu-chi">Thêm tiêu chí CLO</Link></p>}</div></section>
    <div className="khoa-two-col"><section className="khoa-panel"><h2>Phổ điểm toàn khóa</h2><p>Phân bố điểm tổng hợp trên phiếu chấm.</p><div className="score-bars">{(data?.scoreDistribution||[]).map(x=><div className="score-bar-item" key={x.label}><div className="score-bar-value">{x.count}</div><div className="score-bar"><span style={{height:`${Math.max(5,(data?.complete ? x.count/data.complete*100 : 0))}%`}}/></div><small>{x.label}</small></div>)}</div></section><section className="khoa-panel"><h2>Quy trình đánh giá</h2><ol className="khoa-steps"><li><b>GVHD</b><span>Đánh giá tiêu chí và nộp phiếu cho giáo vụ</span></li><li><b>Doanh nghiệp</b><span>Ghi nhận nhận xét từ đơn vị tiếp nhận</span></li><li><b>Hội đồng</b><span>Đối chiếu minh chứng, tổng hợp kết quả</span></li><li><b>Giáo vụ</b><span>Xuất báo cáo phục vụ kiểm định CLO/ABET</span></li></ol></section></div>
    {selected&&<section className="khoa-panel"><div className="khoa-panel-head"><div><h2>Rà soát điểm CLO · {selected.sinhVien} ({selected.maSinhVien})</h2><p>Điểm tổng được tính từ các điểm thành phần và lưu vào phiếu chấm.</p></div><button className="small" onClick={()=>setSelected(null)}>Đóng</button></div><form className="score-edit-form" onSubmit={saveAssessment}>{(data?.criteria||[]).map(c=><label key={c.maTieuChi}><span>{c.maTieuChi} · {c.tenTieuChi}<small>tối đa {c.diemToiDa}</small></span><input type="number" min="0" max={c.diemToiDa} step="0.1" required value={scores[c.maTieuChi]??0} onChange={e=>setScores({...scores,[c.maTieuChi]:e.target.value})}/></label>)}<div className="score-edit-total">Tổng điểm: <strong>{(data?.criteria||[]).reduce((sum,c)=>sum+Number(scores[c.maTieuChi]||0),0).toFixed(2)} / 10</strong></div><div className="khoa-actions"><button className="primary" disabled={saving}>{saving?'Đang lưu…':'Lưu điểm CLO'}</button></div></form></section>}
    <section className="khoa-panel"><div className="khoa-panel-head"><div><h2>Danh sách phiếu đánh giá</h2><p>{rows.length} kết quả phù hợp bộ lọc.</p></div><Link to="/khoa/thong-ke" className="secondary-link">Xem thống kê tiến độ →</Link></div><div className="table-wrap"><table><thead><tr><th>MSSV</th><th>Sinh viên</th><th>Lớp</th><th>Đợt thực tập</th><th>Điểm tổng</th><th>Ngày chấm</th><th>Thao tác</th></tr></thead><tbody>{rows.map(x=><tr key={x.maPhieu}><td>{x.maSinhVien}</td><td>{x.sinhVien}</td><td>{x.lop}</td><td>{x.dot}</td><td><strong>{x.tongDiem ?? 'Chưa chấm'}</strong></td><td>{x.ngayCham ? String(x.ngayCham).slice(0,10) : '—'}</td><td><button className="small" onClick={()=>beginEdit(x)}>{x.tongDiem==null?'Nhập điểm':'Rà soát điểm'}</button></td></tr>)}{!rows.length&&<tr><td colSpan="7">Chưa có phiếu chấm phù hợp.</td></tr>}</tbody></table></div></section>
  </Layout>
}
function Stat({label,value,note}) { return <div className="khoa-stat-card"><small>{label}</small><strong>{value}</strong><span>{note}</span></div> }
