import { useEffect, useState } from 'react'
import Layout from '../../components/Layout'
import apiClient from '../../services/api'

export default function KhoaAccountsPage(){
 const [accounts,setAccounts]=useState([]),[roles,setRoles]=useState([]),[form,setForm]=useState({MaTaiKhoan:'',TenDangNhap:'',MatKhau:'',MaVaiTro:'VT04',OwnerId:''}),[error,setError]=useState(''),[search,setSearch]=useState(''),[roleChoices,setRoleChoices]=useState({}),[ownerChoices,setOwnerChoices]=useState({})
 const load=async()=>{try{const [a,r]=await Promise.all([apiClient.get('/khoa/tai-khoan'),apiClient.get('/khoa/vai-tro')]);setAccounts(a.data);setRoles(r.data);setError('')}catch(e){setError(e.response?.data?.message||'Không tải được tài khoản.')}}
 useEffect(()=>{load()},[])
 const create=async e=>{e.preventDefault();setError('');const owner=form.OwnerId||null;const payload={MaTaiKhoan:form.MaTaiKhoan,TenDangNhap:form.TenDangNhap,MatKhau:form.MatKhau,MaVaiTro:form.MaVaiTro,MaSV:form.MaVaiTro==='VT04'?owner:null,MaGV:form.MaVaiTro==='VT03'?owner:null,MaDaiDien:form.MaVaiTro==='VT05'?owner:null};try{await apiClient.post('/khoa/tai-khoan',payload);setForm({...form,MaTaiKhoan:'',TenDangNhap:'',MatKhau:'',OwnerId:''});await load()}catch(e){setError(e.response?.data?.message||'Không tạo được tài khoản.')}}
 const update=async x=>{try{await apiClient.put(`/khoa/tai-khoan/${encodeURIComponent(x.maTaiKhoan)}`,{TrangThai:x.trangThai==='HoatDong'?'BiKhoa':'HoatDong',MaVaiTro:x.maVaiTro,MaSV:x.maSV,MaGV:x.maGV,MaDaiDien:x.maDaiDien});await load()}catch(e){setError(e.response?.data?.message||'Không cập nhật được tài khoản.')}}
 const changeRole=async x=>{const role=roleChoices[x.maTaiKhoan]||x.maVaiTro;const owner=ownerChoices[x.maTaiKhoan]??x.maSV??x.maGV??x.maDaiDien??null;const payload={TrangThai:x.trangThai,MaVaiTro:role,MaSV:role==='VT04'?owner:null,MaGV:role==='VT03'?owner:null,MaDaiDien:role==='VT05'?owner:null};try{await apiClient.put(`/khoa/tai-khoan/${encodeURIComponent(x.maTaiKhoan)}`,payload);await load()}catch(e){setError(e.response?.data?.message||'Không đổi được vai trò hoặc mã chủ tài khoản.')}}
 const visible=accounts.filter(x=>`${x.tenDangNhap} ${x.maTaiKhoan} ${x.vaiTro?.tenVaiTro||''}`.toLowerCase().includes(search.toLowerCase()))
 return <Layout><div className="khoa-page-heading"><div><span className="eyebrow">QUẢN TRỊ HỌC VỤ</span><h1>Tài khoản & phân quyền</h1><p>Tạo tài khoản học vụ, gán vai trò và khóa hoặc mở khóa quyền truy cập.</p></div><span className="badge">{accounts.length} tài khoản</span></div>{error&&<div className="alert error">{error}</div>}
 <section className="khoa-panel"><h2>Tạo tài khoản</h2><form className="inline-form" onSubmit={create}><input placeholder="Mã tài khoản" value={form.MaTaiKhoan} onChange={e=>setForm({...form,MaTaiKhoan:e.target.value})} required/><input placeholder="Tên đăng nhập" value={form.TenDangNhap} onChange={e=>setForm({...form,TenDangNhap:e.target.value})} required/><input type="password" placeholder="Mật khẩu" value={form.MatKhau} onChange={e=>setForm({...form,MatKhau:e.target.value})} required/><select value={form.MaVaiTro} onChange={e=>setForm({...form,MaVaiTro:e.target.value})}>{roles.map(r=><option key={r.maVaiTro} value={r.maVaiTro}>{r.maVaiTro} · {r.tenVaiTro}</option>)}</select><input placeholder="Mã SV/GV/Đại diện DN" value={form.OwnerId} onChange={e=>setForm({...form,OwnerId:e.target.value})}/><button className="primary">Tạo tài khoản</button></form></section>
 <section className="khoa-panel"><div className="khoa-panel-head"><div><h2>Danh sách tài khoản</h2><p>Vai trò trong hệ thống và trạng thái đăng nhập.</p></div><input placeholder="Tìm tài khoản..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="table-wrap"><table><thead><tr><th>Mã</th><th>Tên đăng nhập</th><th>Vai trò</th><th>Chủ tài khoản</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{visible.map(x=>{const selectedRole=roleChoices[x.maTaiKhoan]||x.maVaiTro;return <tr key={x.maTaiKhoan}><td>{x.maTaiKhoan}</td><td>{x.tenDangNhap}</td><td><select value={selectedRole} onChange={e=>setRoleChoices({...roleChoices,[x.maTaiKhoan]:e.target.value})}>{roles.map(r=><option key={r.maVaiTro} value={r.maVaiTro}>{r.tenVaiTro}</option>)}</select><input className="owner-id-input" placeholder="Mã SV/GV/ĐD" value={ownerChoices[x.maTaiKhoan]??x.maSV??x.maGV??x.maDaiDien??''} onChange={e=>setOwnerChoices({...ownerChoices,[x.maTaiKhoan]:e.target.value})}/><button className="small" onClick={()=>changeRole(x)}>Lưu vai trò</button></td><td>{x.maSV||x.maGV||x.maDaiDien||'—'}</td><td><span className={`badge ${x.trangThai==='HoatDong'?'ok':'bad'}`}>{x.trangThai}</span></td><td><button className="small" onClick={()=>update(x)}>{x.trangThai==='HoatDong'?'Khóa':'Mở khóa'}</button></td></tr>})}{!visible.length&&<tr><td colSpan="6">Không có tài khoản phù hợp.</td></tr>}</tbody></table></div></section>
 <section className="khoa-panel"><h2>Vai trò hệ thống</h2><div className="role-grid">{roles.map(x=><div key={x.maVaiTro}><strong>{x.maVaiTro} · {x.tenVaiTro}</strong><p>{x.moTa}</p></div>)}</div></section></Layout>
}
