import { useEffect, useState } from 'react'
import Layout from '../../components/Layout'
import apiClient from '../../services/api'

const fresh = { maTieuChi: '', tenTieuChi: '', diemToiDa: '' }
export default function KhoaCriteriaPage() {
  const [items,setItems] = useState([]); const [form,setForm] = useState(fresh); const [editing,setEditing] = useState(false); const [error,setError] = useState(''); const [notice,setNotice] = useState('')
  const load = async () => { try { const r=await apiClient.get('/khoa/tieu-chi'); setItems(r.data); setError('') } catch(e) { setError(e.response?.data?.message||'Không tải được tiêu chí.') } }
  useEffect(()=>{load()},[])
  const total=items.reduce((sum,x)=>sum+Number(x.diemToiDa),0)
  const edit=x=>{setForm({maTieuChi:x.maTieuChi,tenTieuChi:x.tenTieuChi,diemToiDa:x.diemToiDa});setEditing(true);setNotice('')}
  const reset=()=>{setForm(fresh);setEditing(false)}
  const save=async e=>{e.preventDefault();setError('');setNotice('');const payload={...form,diemToiDa:Number(form.diemToiDa)};try{if(editing) await apiClient.put(`/khoa/tieu-chi/${encodeURIComponent(form.maTieuChi)}`,payload);else await apiClient.post('/khoa/tieu-chi',payload);setNotice('Đã lưu tiêu chí.');reset();await load()}catch(e){setError(e.response?.data?.message||'Không lưu được tiêu chí.')}}
  const remove=async x=>{if(!window.confirm(`Xóa tiêu chí ${x.maTieuChi}?`))return;try{await apiClient.delete(`/khoa/tieu-chi/${encodeURIComponent(x.maTieuChi)}`);await load()}catch(e){setError(e.response?.data?.message||'Không xóa được tiêu chí. Nếu đã được dùng để chấm điểm, tiêu chí cần được giữ lại.')}}
  return <Layout><div className="khoa-page-heading"><div><span className="eyebrow">CẤU HÌNH HỌC VỤ</span><h1>Tiêu chí đánh giá & chuẩn đầu ra CLO</h1><p>Quản lý danh sách tiêu chí và điểm tối đa dùng cho phiếu đánh giá thực tập.</p></div><div className="khoa-actions"><span className={`badge ${total===10?'ok':'bad'}`}>Tổng điểm tối đa: {total.toFixed(1)} / 10</span></div></div>{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
    <div className="khoa-two-col align-start"><section className="khoa-panel"><h2>{editing?'Chỉnh sửa tiêu chí':'Thêm tiêu chí CLO'}</h2><form className="khoa-form-grid" onSubmit={save}><label>Mã tiêu chí<input value={form.maTieuChi} disabled={editing} onChange={e=>setForm({...form,maTieuChi:e.target.value})} required maxLength="20" placeholder="VD: TC05"/></label><label>Tên tiêu chí<input value={form.tenTieuChi} onChange={e=>setForm({...form,tenTieuChi:e.target.value})} required maxLength="200" placeholder="Tên chuẩn đầu ra"/></label><label>Điểm tối đa<input type="number" min="0.1" step="0.1" value={form.diemToiDa} onChange={e=>setForm({...form,diemToiDa:e.target.value})} required/></label><div className="khoa-actions"><button className="primary">{editing?'Cập nhật':'Thêm tiêu chí'}</button>{editing&&<button type="button" className="small" onClick={reset}>Hủy sửa</button>}</div></form><p className="hint">Tiêu chí đã được dùng trong phiếu chấm sẽ không thể xóa để giữ nguyên dữ liệu lịch sử.</p></section><section className="khoa-panel"><h2>Nguyên tắc đánh giá</h2><ul className="khoa-notes"><li>Mỗi tiêu chí có mã duy nhất và điểm tối đa lớn hơn 0.</li><li>Điểm chấm của sinh viên được tổng hợp theo đợt thực tập.</li><li>Các tiêu chí hiện dùng để tạo ma trận thống kê CLO/ABET.</li></ul><a className="secondary-link" href="/khoa/hoi-dong">Mở bảng thống kê CLO →</a></section></div>
    <section className="khoa-panel"><div className="khoa-panel-head"><div><h2>Danh mục tiêu chí</h2><p>{items.length} tiêu chí trong hệ thống.</p></div></div><div className="table-wrap"><table><thead><tr><th>Mã</th><th>Tiêu chí / chuẩn đầu ra</th><th>Điểm tối đa</th><th>Thao tác</th></tr></thead><tbody>{items.map(x=><tr key={x.maTieuChi}><td>{x.maTieuChi}</td><td>{x.tenTieuChi}</td><td>{x.diemToiDa}</td><td><button className="small" onClick={()=>edit(x)}>Sửa</button>{' '}<button className="small danger-btn" onClick={()=>remove(x)}>Xóa</button></td></tr>)}{!items.length&&<tr><td colSpan="4">Chưa có tiêu chí.</td></tr>}</tbody></table></div></section></Layout>
}
