/* =====================================================================
   03_create_constraints.sql
   Khai báo toàn bộ khóa ngoại (FK) giữa 18 bảng.
   ===================================================================== */
USE InternshipManagementDb;
GO

ALTER TABLE DAIDIENDOANHNGHIEP
    ADD CONSTRAINT FK_DAIDIENDN_CONGTY FOREIGN KEY (maCongTy) REFERENCES CONGTY(maCongTy);
GO

ALTER TABLE HOSONANGLUC
    ADD CONSTRAINT FK_HOSONANGLUC_SINHVIEN FOREIGN KEY (maSinhVien) REFERENCES SINHVIEN(maSV);
GO

ALTER TABLE DANGKYTHUCTAP
    ADD CONSTRAINT FK_DANGKY_SINHVIEN FOREIGN KEY (maSinhVien) REFERENCES SINHVIEN(maSV),
    CONSTRAINT FK_DANGKY_CONGTY   FOREIGN KEY (maCongTy)   REFERENCES CONGTY(maCongTy),
    CONSTRAINT FK_DANGKY_DOT      FOREIGN KEY (maDot)      REFERENCES DOTTHUCTAP(maSo);
GO

ALTER TABLE PHONGVAN
    ADD CONSTRAINT FK_PHONGVAN_SINHVIEN FOREIGN KEY (maSinhVien) REFERENCES SINHVIEN(maSV),
    CONSTRAINT FK_PHONGVAN_CONGTY   FOREIGN KEY (maCongTy)   REFERENCES CONGTY(maCongTy);
GO

ALTER TABLE PHANBOTHUCTAP
    ADD CONSTRAINT FK_PHANBO_SINHVIEN FOREIGN KEY (maSinhVien) REFERENCES SINHVIEN(maSV),
    CONSTRAINT FK_PHANBO_CONGTY   FOREIGN KEY (maCongTy)   REFERENCES CONGTY(maCongTy),
    CONSTRAINT FK_PHANBO_DOT      FOREIGN KEY (maDot)      REFERENCES DOTTHUCTAP(maSo);
GO

ALTER TABLE GVHUONGDAN
    ADD CONSTRAINT FK_GVHUONGDAN_GV FOREIGN KEY (maGiangVien) REFERENCES GIANGVIEN(maGV),
    CONSTRAINT FK_GVHUONGDAN_SV FOREIGN KEY (maSinhVien)  REFERENCES SINHVIEN(maSV);
GO

ALTER TABLE HUONGDANDOANHNGHIEP
    ADD CONSTRAINT FK_HDDN_DAIDIEN FOREIGN KEY (maDaiDien) REFERENCES DAIDIENDOANHNGHIEP(maSo),
    CONSTRAINT FK_HDDN_DANGKY  FOREIGN KEY (maDangKy)  REFERENCES DANGKYTHUCTAP(maDangKy);
GO

ALTER TABLE TIENDOTHUCTAP
    ADD CONSTRAINT FK_TIENDO_DOT FOREIGN KEY (maDot) REFERENCES DOTTHUCTAP(maSo);
GO

ALTER TABLE PHIEUCHAMDIEM
    ADD CONSTRAINT FK_PHIEUCHAM_GVHD    FOREIGN KEY (maGV)          REFERENCES GVHUONGDAN(maSo),
    CONSTRAINT FK_PHIEUCHAM_HDDN    FOREIGN KEY (maDoanhNghiep) REFERENCES HUONGDANDOANHNGHIEP(maSo),
    CONSTRAINT FK_PHIEUCHAM_DOT     FOREIGN KEY (maDot)         REFERENCES DOTTHUCTAP(maSo);
GO

ALTER TABLE CHITIETCHAMDIEM
    ADD CONSTRAINT FK_CTCD_PHIEU FOREIGN KEY (maPhieuCham) REFERENCES PHIEUCHAMDIEM(maPhieu),
    CONSTRAINT FK_CTCD_TIEUCHI FOREIGN KEY (maTieuChi)   REFERENCES TIEUCHI(maTieuChi);
GO

ALTER TABLE GOIYCONGTY
    ADD CONSTRAINT FK_GOIY_HOSO   FOREIGN KEY (maHoSo)   REFERENCES HOSONANGLUC(maHoSo),
    CONSTRAINT FK_GOIY_CONGTY FOREIGN KEY (maCongTy) REFERENCES CONGTY(maCongTy);
GO

ALTER TABLE GIOITHIEU
    ADD CONSTRAINT FK_GIOITHIEU_GV     FOREIGN KEY (maGV)     REFERENCES GIANGVIEN(maGV),
    CONSTRAINT FK_GIOITHIEU_CONGTY FOREIGN KEY (maCongTy) REFERENCES CONGTY(maCongTy);
GO

ALTER TABLE DEXUATCONGTY
    ADD CONSTRAINT FK_DEXUAT_CONGTY FOREIGN KEY (maCongTy) REFERENCES CONGTY(maCongTy),
    CONSTRAINT FK_DEXUAT_SV     FOREIGN KEY (maSV)      REFERENCES SINHVIEN(maSV),
    CONSTRAINT FK_DEXUAT_GV     FOREIGN KEY (maGV)      REFERENCES GIANGVIEN(maGV);
GO
