import {useEffect,useState} from 'react'
import apiClient from '../../services/api'
import Layout from '../../components/Layout'
export default function AdminPage(){
 const [accounts,setAccounts]=useState([]),[roles,setRoles]=useState([]),[error,setError]=useState(''); const [form,setForm]=useState({MaTaiKhoan:'',TenDangNhap:'',MatKhau:'',MaVaiTro:'VT04',OwnerId:''})
 const load=async()=>{try{const [a,r]=await Promise.all([apiClient.get('/admin/accounts'),apiClient.get('/admin/roles')]);setAccounts(a.data);setRoles(r.data)}catch(e){setError(e.response?.data?.message||'Không tải được dữ liệu')}}; useEffect(()=>{load()},[])
 const create=async e=>{e.preventDefault();setError('');const owner=form.OwnerId||null;const payload={MaTaiKhoan:form.MaTaiKhoan,TenDangNhap:form.TenDangNhap,MatKhau:form.MatKhau,MaVaiTro:form.MaVaiTro,MaSV:form.MaVaiTro==='VT04'?owner:null,MaGV:form.MaVaiTro==='VT03'?owner:null,MaDaiDien:form.MaVaiTro==='VT05'?owner:null};try{await apiClient.post('/admin/accounts',payload);setForm({MaTaiKhoan:'',TenDangNhap:'',MatKhau:'',MaVaiTro:'VT04',OwnerId:''});load()}catch(e){setError(e.response?.data?.message||'Không tạo được tài khoản')}}
 const update=async x=>{try{await apiClient.put(`/admin/accounts/${x.maTaiKhoan}`,{TrangThai:x.trangThai==='HoatDong'?'BiKhoa':'HoatDong',MaVaiTro:x.maVaiTro,MaSV:x.maSV,MaGV:x.maGV,MaDaiDien:x.maDaiDien});load()}catch(e){setError(e.response?.data?.message||'Không cập nhật được tài khoản')}}
 return <Layout><div className="page-head"><div><span className="eyebrow">ADMIN</span><h2>Quản trị người dùng & phân quyền</h2></div></div>{error&&<div className="alert error">{error}</div>}<div className="info-card"><h3>Tạo tài khoản</h3><form className="inline-form" onSubmit={create}><input placeholder="Mã tài khoản" value={form.MaTaiKhoan} onChange={e=>setForm({...form,MaTaiKhoan:e.target.value})} required/><input placeholder="Tên đăng nhập" value={form.TenDangNhap} onChange={e=>setForm({...form,TenDangNhap:e.target.value})} required/><input placeholder="Mật khẩu" value={form.MatKhau} onChange={e=>setForm({...form,MatKhau:e.target.value})} required/><select value={form.MaVaiTro} onChange={e=>setForm({...form,MaVaiTro:e.target.value})}>{roles.map(r=><option key={r.maVaiTro} value={r.maVaiTro}>{r.maVaiTro} - {r.tenVaiTro}</option>)}</select><input placeholder="Mã SV/GV/ĐD" value={form.OwnerId} onChange={e=>setForm({...form,OwnerId:e.target.value})}/><button className="primary">Tạo</button></form></div><div className="info-card"><h3>Danh sách tài khoản</h3><div className="table-wrap"><table><thead><tr><th>Mã</th><th>Đăng nhập</th><th>Vai trò</th><th>Trạng thái</th><th></th></tr></thead><tbody>{accounts.map(x=><tr key={x.maTaiKhoan}><td>{x.maTaiKhoan}</td><td>{x.tenDangNhap}</td><td>{x.vaiTro?.tenVaiTro}</td><td><span className={`badge ${x.trangThai==='HoatDong'?'ok':'bad'}`}>{x.trangThai}</span></td><td><button className="small" onClick={()=>update(x)}>{x.trangThai==='HoatDong'?'Khóa':'Mở khóa'}</button></td></tr>)}</tbody></table></div></div><div className="info-card"><h3>Vai trò</h3><div className="role-grid">{roles.map(x=><div key={x.maVaiTro}><strong>{x.maVaiTro} · {x.tenVaiTro}</strong><p>{x.moTa}</p></div>)}</div></div></Layout>
}
